### PR TITLE
Sargeras

### PR DESCRIPTION
**Pull request by Smerdokryl**
What this does is quite obvious: adds Sargeras, the Dark Titan, as a god choice for KillThemAll.

I have originally intended these files to be used with the Scepter of Sargeras, via [ArtifactWhispers](https://www.curseforge.com/wow/addons/artifactwhispers). However, the addon seems to have been abandoned.

In hopes of more specific events such as killing an enemy or visiting a location, I have made some extra sound files. I realise they are not yet usable with this addon, but I provided the audio files and the path references for possible future additions.

### CODE REVIEW

**Comment by Thex-PiedDroit** [comment]
Hi, thank you so much for you contribution, i really appreciate it!
However, in KillThemAll i do not use additional sound files, therefore i cannot merge your pull request as is. Also, i think it would be best fitted as an optional module than directly into the main addon, therefore i'd encourage you to check out how i made my modules, such as [LichKing](https://www.curseforge.com/wow/addons/killthemall_lichking), and do the same yourself (you can simply copy one of them and change the names around). You could then post the addon yourself and i'll link it in my main addon's description

If you'd need help doing that, don't hesitate to ask me, but i think it's fairly straight forward :)

**Comment by Thex-PiedDroit** [comment]
Oh my bad, that's what you already did! Sorry didn't see that from my phone!

Then all i'd ask of you would be to remove the soundfiles from the commit, make sure it works, and i'll merge it

**Comment by Thex-PiedDroit** [comment]
For the files that cannot yet be used, you could maybe make some other list members like "g_sargeras.m_enemyDeathSoundFilesList" or similar, using the original data path. That way, if that feature is added some day, you won't have to change the addon at all ;)

**Comment by Smerdokryl** [comment]
> Then all i'd ask of you would be to remove the soundfiles from the commit, make sure it works, and i'll merge it

The number of Sargeras' sound files is very limited already, and so my only option really is to cut pieces out and use them. Since this is an optional module, it's up to people whether they like to download custom sound files. If you believe that sound files should not be used at all, I do not mind uploading this as a separate thing on curse to avoid direct affiliation with the main addon.

> For the files that cannot yet be used, you could maybe make some other list members like "g_sargeras.m_enemyDeathSoundFilesList" or similar, using the original data path

Will do!

**Comment by Thex-PiedDroit** [comment]
> The number of Sargeras' sound files is very limited already, and so my only option really is to cut pieces out and use them. Since this is an optional module, it's up to people whether they like to download custom sound files. If you believe that sound files should not be used at all, I do not mind uploading this as a separate thing on curse to avoid direct affiliation with the main addon.

Do you mean those files are not present in the game's data already?

**Comment by Smerdokryl** [comment]
> Do you mean those files are not present in the game's data already?

I took the original files and cut out pieces which can be used separately. For example, when Sargeras says "Become the instrument of my wrath once again, Aggramar, bla-bla-bla", I edited the sound file to only say "Become the instrument of my wrath.", which is something that could be said to the player. Similarly with other files.

The sounds that can be used in their original form have been linked properly as existing game files.

**Comment by Thex-PiedDroit** [comment]
Ah, got it. Awesome, then it's all good with me.
Let me know when i can merge, and i invite you to create the module's page yourself so the credit will go entirely to you. I'll link it on the main addon's page of course

**Comment by Smerdokryl** [comment]
Done the editing and added a couple of new lines. Feel free to merge.

I shall make a curse page as you suggested and provide a link here in the comments, so don't close the pull request just yet

**Comment by Smerdokryl** [comment]
Once approved, the module will be at https://wow.curseforge.com/projects/killthemall_sargeras

**Pull request merged**
