### PR TITLE
NZotz, Uncorrupted/Light Ashbringer, XalAtath update

### PR DESCRIPTION
**Pull request by xTwoSouls**
Hi Thex_, I hope it's right what I'm doing here, never used GitHub before.
You should finde some ZIP files in this message. :)

[KillThemAll_NZoth.zip](https://github.com/Thex-PiedDroit/WoWAddons/files/3383141/KillThemAll_NZoth.zip)
[KillThemAll_LightAshbringer.zip](https://github.com/Thex-PiedDroit/WoWAddons/files/3383145/KillThemAll_LightAshbringer.zip)
[KillThemAll_XalAtath.zip](https://github.com/Thex-PiedDroit/WoWAddons/files/3383146/KillThemAll_XalAtath.zip)

### CODE REVIEW

**Comment by Thex-PiedDroit** [comment]
Thank you! But yeah that's not exactly it; you should get your repo set to a folder called WoWAddons, in which you'd have the three folders unzipped; then make a commit with this so it can actually change the files directly.
If that's too complex for you it's alright i can just download your zip files from here and do it myself :)

**Comment by xTwoSouls** [comment]
How do I do that? I have to fill in two boxes "base" and "compare", to what do I have to set them? Is that wwhat you mean with repo?
Sorry, I'm really new to this.

**Comment by Thex-PiedDroit** [comment]
No need to apologize!
No it's not that, you'd need to first clone the project on your computer. The resulting folder is what is called your local repo(sitory). From there, replace the files with your modified files (just extract over the created folder yeah) and then, with a git client (the base github client for example, or SourceTree or whatnot), create a commit including all your changes. Then you'd push that and create a merge request from the website, to merge your branch to mine.

Hope this is clear; don't hesitate to ask if there are blurry spots! Also i'm telling you this only if you want to actually learn how to use github, so if you're not actually interested to learn that or what, do tell me and i'll do the things myself it's no bother :)

**Comment by xTwoSouls** [comment]
Ok, after reading your reply and looking into a guide this seems more complicated than editing your addon. xD
I think for now it's the best if you upload the files. It would take hours for me to work this out.

**Comment by Thex-PiedDroit** [comment]
Hahaha ok no problem!
Thanks for your stuff m8 :)

**Pull request closed without merging**
